# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
project 'Jarvis++.xcodeproj'
workspace 'Jarvis'
target 'Jarvis++' do
  # Comment the next line if you don't want to use dynamic frameworks
  inherit! :search_paths
  #use_frameworks!

  # Pods for Jarvis++
  pod 'CocoaHTTPServer', :git => 'https://github.com/robbiehanson/CocoaHTTPServer.git'
  pod 'PaperTrailLumberjack', :git => 'https://github.com/greenbits/papertrail-lumberjack-ios.git'
  #pod 'KIF', :git => 'https://github.com/kif-framework/KIF.git'
  #pod 'KIF', '~> 3.7.8'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#    end
#  end
#end
