//
//  Consts.h
//  Jarvis++
//
//  Created by versx on 3/7/20.
//

@interface Consts : NSObject

extern NSString *BIRTHDAY_USER_DEFAULT_KEY;
extern NSString *TOKEN_USER_DEFAULT_KEY;
extern NSString *LOGIN_USER_DEFAULT_KEY;

extern NSNumber *DEFAULT_BDAY;

extern NSNumber *DEFAULT_MIN_LEVEL;
extern NSNumber *DEFAULT_MAX_LEVEL;
extern NSNumber *DEFAULT_PORT;
extern NSNumber *DEFAULT_TARGET_MAX_DISTANCE;
extern NSNumber *DEFAULT_POKEMON_MAX_TIME;
extern NSNumber *DEFAULT_RAID_MAX_TIME;
extern NSNumber *DEFAULT_ENCOUNTER_DELAY;
extern NSNumber *DEFAULT_MAX_EMPTY_GMO;
extern NSNumber *DEFAULT_MAX_FAILED_COUNT;
extern NSNumber *DEFAULT_MAX_NO_QUEST_COUNT;
extern NSNumber *DEFAULT_MAX_WARNING_TIME_RAID;
extern NSNumber *DEFAULT_MIN_DELAY_LOGOUT;
extern BOOL DEFAULT_ENABLE_ACCOUNT_MANAGER;
extern BOOL DEFAULT_ULTRA_QUESTS;
extern BOOL DEFAULT_DEPLOY_EGGS;

@end
